default_language_version:
  python: python3.8
exclude: "[a-zA-Z]*/(migrations)/(.)*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--config=server/setup.cfg]
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--config=server/pyproject.toml]
        # args: [--config=server/pyproject.toml, --check, --diff,]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.3
    hooks:
      - id: isort
        name: Reorder python imports
