language: python

python:
  - 3.8

services:
  - docker

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker-compose exec web coverage run manage.py test apps

after_script:
  - docker-compose down
