language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm run test:cypress && npm test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
