version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  web:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/assets/staticfiles
      - media_volume:/usr/src/assets/mediafiles
    expose:
      - 8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    links:
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/assets/staticfiles
      - media_volume:/usr/src/assets/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:latest
volumes:
  postgres-data:
  static_volume:
  media_volume:
