version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: taxi-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  client:
    build: ./client
    image: docker.pkg.github.com/ajithpmohan/taxi-app/client-dev:0.1
    container_name: taxi-client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - ./client/.env.dev
    depends_on:
      - postgres
      - server
    stdin_open: true
  server:
    build: ./server
    image: docker.pkg.github.com/ajithpmohan/taxi-app/server-dev:0.1
    container_name: taxi-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/web/
    ports:
      - "8100:8000"
    env_file:
      - ./server/.env.dev
    depends_on:
      - postgres
    links:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
    container_name: taxi-redis

volumes:
  postgres-data:
