version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: taxi-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  web:
    build: ./web
    container_name: taxi-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - "9000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    links:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
    container_name: taxi-redis
volumes:
  postgres-data:
