version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: docker.pkg.github.com/ajithpmohan/taxi-app/frontend-prod:1.0
    ports:
      - 1338:80
    depends_on:
      - db
      - backend-asgi
      - backend-wsgi
  # backend-asgi container is for handling websocket req/res.
  backend-asgi:
    build:
      context: ./server
      dockerfile: Dockerfile.asgi.prod
    image: docker.pkg.github.com/ajithpmohan/taxi-app/backend-asgi-prod:1.0
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    expose:
      - 8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    links:
      - redis
  # backend-wsgi container is for handling normal http req/res.
  backend-wsgi:
    build:
      context: ./server
      dockerfile: Dockerfile.wsgi.prod
    image: docker.pkg.github.com/ajithpmohan/taxi-app/backend-wsgi-prod:1.0
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/assets/staticfiles
      - media_volume:/usr/src/app/assets/mediafiles
    expose:
      - 8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    links:
      - redis
  nginx:
    build: ./nginx
    image: docker.pkg.github.com/ajithpmohan/taxi-app/nginx-prod:1.0
    volumes:
      - static_volume:/usr/src/app/assets/staticfiles
      - media_volume:/usr/src/app/assets/mediafiles
    ports:
      - 1337:80
    depends_on:
      - backend-asgi
      - backend-wsgi
  redis:
    image: redis:latest
volumes:
  postgres-data:
  static_volume:
  media_volume:
