version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: taxi-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  client:
    build: ./client
    container_name: taxi-client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/node_modules
    ports:
      - "4200:4000"
    depends_on:
      - postgres
      - server
    stdin_open: true
  server:
    build: ./server
    container_name: taxi-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - "8100:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    links:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
    container_name: taxi-redis
volumes:
  postgres-data:
