version: '3'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DATABASE=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    stdin_open: true
    tty: true
